export const FILE_NAME = '.settings.json'
export const KEY_BACKEND_HOST = 'backendHost'
export const KEY_BACKEND_PORT = 'backendPort'
export const KEY_TS_CLIENT_GEN_DIR = 'tsClientGenDir'
export const KEY_RUST_CLIENT_GEN_DIR = 'rustClientGenDir'
